### ISSUE TITLE
Custom rep?

### ISSUE THREAD

**Issue by typedrat** [Bathtor/EPSheet#62]
There doesn't seem to be a way to enter a custom type of reputation.

**Comment by Bathtor** [comment]
Indeed, which I recognise is an issue, but not one that is trivial to fix.

The problem is that rep is tracked per identity on the sheet (which the official rules don't necessarily state, but makes sense in my opinion) and identities are a repeating section, so you can add custom ones. But Roll20 does not allow nested repeating sections, so I can't make rep networks in a way that you can add custom ones per identity.

I see essentially two ways around this:
1. Add a fixed number of customisable rep entries to *every* identity and make them hidden if not in use.
2. Make *all* the rep entries customisable and only use the current names as default values. This would allow people to either completely replace existing networks, or simply add a second identity entry for each actual identity with the new custom rep networks in it.

At the moment I'm slightly in favour of option 2, because it's easier to implement and causes less bloat on the sheet (i.e. fewest new fields added to existing sheets that don't require this feature). But I'm open to opinions and suggestions on the matter.

**Comment by typedrat** [comment]
Is this something that could be brought upstream? Have nested repeating sections been requested before? It doesn't seem hard.

Alexis Williams

**Comment by Bathtor** [comment]
Yes, there appears to be an [entry for that](https://app.roll20.net/forum/post/2942465/nested-repeating-sections/?pageforid=2942465#post-2942465) in the suggestions forum for 2 years. But since it's an issue only sheet authors know it has few votes, and Roll20 isn't typically very good at implementing things, even if they have hundreds of votes. I wouldn't hold my breath.

**Comment by Bathtor** [comment]
See https://github.com/Bathtor/EPSheet/wiki/Identities#custom-reputation-networks for usage.
