### ISSUE TITLE
Morph boni not shown in aptitudes in core tab

### ISSUE THREAD

**Issue by Akashar-dev** [Bathtor/EPSheet#75]
Skill boni work just fine
on chrome

**Comment by Bathtor** [comment]
Hi and thank you for your bug report.

I have tried to reproduce the issue in Chrome with a fresh campaign using the sheet and script from the Roll20 dropdown, but it seems to work fine for me (see attached image).

<img width="934" alt="Screenshot 2020-07-18 12 33 29" src="https://user-images.githubusercontent.com/596721/87850837-83ad4400-c8f3-11ea-82fe-6371915f3f52.png">

Could you perhaps provide me a concrete reproduction path starting from a fresh character sheet, after double checking that you are using the latest version of sheet and script respectively?

In particular, if you entered the morph's information manually instead of importing from the compendium, show me exactly the syntax you used, i.e. what is written in the morph's "APTITUDE BONI" field. A screenshot would be best. The most likely issue is that it's a parsing problem with the input, causing the sheet workers to ignore the field.

If you know how to use developer tools in Chrome, you can also search the Javascript Console for "ERROR" to see if the sheet workers encountered any issues.

**Comment by Akashar-dev** [comment]
Thank you for the quick and high quality answer. Reading it made me look better on the sheet and I saw that the "use api script" option wasn't ticked. It had not bothered me until then as everything else seemed to work just fine. (as I saw skills boni and other things being calculated right, I didn't think I needed anything more.)
You mentionning scripts in your answer made me realise they were required.
Thanks again for your fast answer (and for your amazing work on this !)
